spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_DB_HOST}:${POSTGRESQL_DB_PORT}/${POSTGRESQL_DB}?currentSchema=${POSTGRESQL_DB_SCHEMA}
    username: ${POSTGRESQL_DB_USER_NAME}
    password: ${POSTGRESQL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.yaml
    enabled: true
  redis:
    host: ${AUTH_REDIS_HOST}
    port: ${AUTH_REDIS_PORT}
    database: ${AUTH_REDIS_DB}
    timeout: ${AUTH_REDIS_TIMEOUT}

redis:
  registration:
    otp:
      key-prefix : "RegistrationOtp:"
      ttl : 5 # in minutes
